server:
  port: 9080

spring:
  application:
    name: "order"
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      schema-locations:
        - classpath:init-schema.sql
      #data-locations:
      #  - classpath:init-data.sql
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}
      cluster: local
      # Micrometer Metrics configures this attribute with "unknown value".
      # It should probably be autoconfigured correctly by Spring Boot.
      "service.name": ${spring.application.name}

  # Traces-specific OpenTelemetry configuration
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

logging:
  include-application-name: false
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    com:
      sam:
        order: INFO

otel:
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none