global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'order'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'order:9080' ]
  - job_name: 'payment'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'payment:9180' ]
  
